# Generated by Django 5.2.15 on 2026-06-16 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('marked', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
